### ISSUE TITLE
Server quits when no SRS found

### ISSUE THREAD

**Issue by davidshumway** [galbiston/geosparql-jena#11]
Is this expected? Although the library is essentially for GeoSPARQL, there are use cases for running vanilla RDF (without any GeoSPARQL). For example, simply to test that the RDF is valid.

https://github.com/galbiston/geosparql-jena/blob/c1625a6a8ad41f788c25bb1c91b9b8bdd42656c2/src/main/java/io/github/galbiston/geosparql_jena/configuration/GeoSPARQLOperations.java#L497

```bash
19:45:58 ERROR Main       :: GeoSPARQL Server:  Exiting - No SRS found. Check 'http://www.opengis.net/ont/geosparql#hasSerialization' or 'http://www.w3.org/2003/01/geo/wgs84_pos#lat'/'http://www.w3.org/2003/01/geo/wgs84_pos#lon' predicates are present in the source data. Hint: Inferencing with GeoSPARQL schema may be required.:
```

**Comment by galbiston** [comment]
This project is no longer maintained. It has been incorporated as the `GeoSPARQL` module of the Apache Jena project. Questions should be directed there and this issue may have been resolved in a later version.
