### ISSUE TITLE
Bug: CustomCoordinateSequence::setOrdinate missing break statements

### ISSUE THREAD

**Issue by pneuschwander** [galbiston/geosparql-jena#4]
https://github.com/galbiston/geosparql-jena/blob/master/src/main/java/io/github/galbiston/geosparql_jena/implementation/jts/CustomCoordinateSequence.java#L441

There should be "break" Statements in that switch. 
Currently there is a fallthrough manipulating Z and M values.

**Comment by galbiston** [comment]
Thanks for reporting this. These were fixed a long time ago when you reported and the comment wasn't updated.
