### ISSUE TITLE
Resolution conflict between org.geotools:gt-referencing and org.apache.sis-core.sis-referencing

### ISSUE THREAD

**Issue by lisha992610** [galbiston/geosparql-jena#5]
Hi. 
Thank you for the useful GEOSPARL library. 

I am trying to add this library as a dependency for my project which use org.geotools:gt-referencing module. It seems that org.apache.sis-core.sis-referencing (dependency for this GEOSPARQL library) has hugh incompability with "org.geotools:gt-referencing / gt-opengis".  

It throws me such error like : "Caused by: java.lang.ArrayStoreException: org.geotools.referencing.factory.epsg.DefaultFactory"

Is this problem aware from your experience? Do you have any solutation/ suggestion/ advice for resolving the problem?

I appreciate for any suggestion and advice. Thank you.

**Comment by galbiston** [comment]
Apologies, I wasn't aware that you had raised this issue. This library is integrated into Apache Jena and is no longer maintained. 

In belated answer to your question, I don't think there is a resolution as they both are implementations of the same geospatial API. This means that the package and class structures are identical. I considered using the GeoTools library but found it problematic in itself, which lead to using SIS Referencing. Perhaps consider if SIS Referencing can meet your needs.
