### ISSUE TITLE
geof:sfContains(polygon, points) implemented?

### ISSUE THREAD

**Issue by davidshumway** [galbiston/geosparql-jena#9]
Is geof:sfContains(polygon, points) implemented? I notice a reference to it in the documentation but I'm not following whether it's functional and if so how to implement it.

Prefixes:
```rdf
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix spa: <http://jena.apache.org/spatial#>
prefix spaf: <http://jena.apache.org/function/spatial#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix geo: <http://www.opengis.net/ont/geosparql#> 
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix sf: <http://www.opengis.net/ont/sf#> 
prefix ex: <http://www.example.org/> 
prefix ogis: <http://www.opengis.net/def/uom/OGC/1.0/>
```

Points are defined in (n3), for example:
```rdf
ex:geom-11 a geo:Geometry ; 
ex:latitude "39.27"^^xsd:decimal ; #extraneous but may be helpful
ex:longitude "-103.19"^^xsd:decimal ; #extraneous but may be helpful
geo:asWKT "<http://www.opengis.net/def/crs/EPSG/0/4326> POINT(39.27 -103.19)"^^geo:wktLiteral .
```

Then defining and utilizing a bounding polygon does not seem to be working. For example:
```sparql
SELECT (count(*) as ?c) WHERE {
  ?f geo:asWKT ?wkt . 
  BIND("POLYGON((54.31 -116.54, 33.73 -115.92, 33.28 -91.93, 53.74 -93.60, 54.31 -116.54))"^^geo:wktLiteral AS ?poly) .
  FILTER(geof:sfContains(?poly, ?point))
}
# returns 0 results
```

Whereas a circle or box using `spa` is working and returns results as expected:
```sparql
SELECT (count(*) as ?c) WHERE {
  ?feature spa:withinBox(54.32 -116.54 33.28 -91.93)
}
```
```sparql
SELECT (count(*) as ?c) WHERE {
  ?feature spa:withinCircle(39.26 -103.23 1000)
}
```

**Comment by galbiston** [comment]
`geof:sfContains(?poly, ?point)` is implemented and has a unit test.

The example query does not bind `?point` to any values. Perhaps try `?f geo:asWKT ?point .`

This is not the maintained project for GeoSPARQL Jena. It has all been transferred to the main Apache Jena project.

**Comment by davidshumway** [comment]
Thanks for mentioning the unit test. Forgot to look there.

`?f geo:asWKT ?wkt` was indeed incorrect, but this doesn't solve the issue.

i.e. still no results for this:
```sparql
SELECT (count(*) as ?c) WHERE {
  ?f geo:asWKT ?point . 
  BIND("POLYGON((54.31 -116.54, 33.73 -115.92, 33.28 -91.93, 53.74 -93.60, 54.31 -116.54))"^^geo:wktLiteral AS ?poly) .
  FILTER(geof:sfContains(?poly, ?point))
}
```

Perhaps defining the polygon as both a `geo:Geometry` and a `geo:SpatialObject` and/or utilizing `geo:hasSerialization` (https://github.com/galbiston/geosparql-jena/blob/c1625a6a8ad41f788c25bb1c91b9b8bdd42656c2/src/test/java/io/github/galbiston/geosparql_jena/geo/topological/EmptyUpdateTest.java#L62)?

**Comment by galbiston** [comment]
The arguments of `geof:sfContains` are geometry literals. The other properties aren't required unless you are trying to use property functions and the query re-write mechanism.

The point geometry is using SRS `<http://www.opengis.net/def/crs/EPSG/0/4326>` (lat/lon) while the polygon geometry is using the default SRS `<http://www.opengis.net/def/crs/OGC/1.3/CRS84>` (see page 16 of the GeoSPARQL standard - lon/lat). The conversion of SRS is handled automatically. However, the values of the polygon are not adjusted to reflect the reversal of the coordinate axis.
